### ISSUE TITLE
Line-cutting

### ISSUE THREAD

**Issue by DBChoi85** [DBChoi85/Hanja_DKU#1]
sample01의 경우 row방향으로 시도할 시 외각 테두리의 검출 및 제거가 가능했으나,

sample02의 경우 외각 테두리의 검출 및 제거가 불가능

이에대한 개선필요

**Comment by 3211187** [comment]
1. 이미지의 가운데 행을 기준으로 아래위로 일정비율로 크기를 잡아 이미지를 자른다
2. 자른 이미지를 가지고  글자사이를 자를 기준을 정한다. (기준은 Line_segment 알고리즘 이용해서 정함)
3. 정해진 기준을 원본이미지에 적용시켜 Crop한다.
((현재 Mask R-CNN으로 최종 segment작업을 진해하고 있기 때문에, Traindata 형식에 맞춰 세로열로 한번만 잘라 사용중))
