### ISSUE TITLE
Mask R-CNN에서 Train_Data의 복잡성 

### ISSUE THREAD

**Issue by 3211187** [DBChoi85/Hanja_DKU#11]
문제 : 
Mask R-CNN의 Train_Data는 일반 CNN의 Train_Data처럼 단순히 이미지만 필요로 하지 않는다.  이미지 내에있는 객체의 위치를 알려줄 좌표로된 영역이 추가로 필요하다. 이 영역을 설정해 주기 위해서는 대게 영역을 일일이 지정하고 JSON파일로 저장시킬수 있는 Tool을 이용한다.  이런 Tool을 사용하더라도 Train_Data를 준비하는데는 꽤 많은 시간과 인력을 필요로 한다. 그래서 우리는 Mask R-CNN의 결과로 나온 Mask영역을 좌표로 받아 Train_Data의 객체 영역으로 활용하고자 하는 아이디어를 고안해 냈다.

해결 : 
1. Mask R-CNN의 결로나온 객체의 Mask영역을 좌표로 받는다
 - 
 - 

2. 받은 좌표를 JSON파일로 변화하여 Train_Data로 이용한다.
 - 
 -

**Comment by 3211187** [comment]
추정
--
Mask R-CNN의 test결과중 잘나온 결과들을 활용해 train_data로 이용한다면 좋겠지만, 항상 완벽히 좋은 결과만 나온다는 보장이 없다. 그래서 나온 결과들의 Mask영역을 수동적으로 수정해주는 방법도 생각하고 있다. 그 방법으로 우리가 사용중인 VGG Image Annotator Tool을 이용해 mask영역을 수정하는 방법이다.

1. 나온 결과의 mask영역의 좌표를 받는다.
2. 받은 좌표들을 VGG Image Annotator Tool을 이용해 만든 Json파일 형식처럼 json파일로 변환한다.
3. VGG Image Annotator 에 접속하여 해당 이미지를 불러온다.
4. 사이트의 import기능을 활용하여 json파일을 이미지에 적용시킨다.
5. 적용된 테두리를 수정한후 다시 json파일로 저장한다.

**Comment by DBChoi85** [comment]
1. 강교수님의 알고리즘이 늦어진다면 위 방법을 우선시 하여 제작하는게 시간을 단축이 가능할 듯함.

2. VGG Image Annotator Tool을 사용법을 한자 학생들에게도 교육할 예정이기에 인력 사용이 가능할 것이라 예상

**Comment by 3211187** [comment]
Mask 영억을 받으면서 생긴 문제점들
---
해당 이미지 범위내에서 object가 존재하는지 안하는지를(1 or 0) 표시한 mask행열을 가지고 contours함수(임계치를 기준으로 넘는 공간과 안넘는 공간의 경계를 표시함)을 이용해 글자의 좌표를 알아 낸다.
 - 픽셀단위로 좌표를 읽다 보니 너무 촘촘하게 좌표가 표시되어 수정하는데 어려움이 존재한다.
![image](https://user-images.githubusercontent.com/32090903/63417825-ff311780-c43c-11e9-8ffa-cfc8734ea799.png)

해결
---
 ~~~
                if i_1%8 ==0:
                    x1.append(v[i_1, 0])
                    y1.append(v[i_1, 1])
            x1.append(v[0, 0])
            y1.append(v[0, 1])
~~~
 - 8번중 1번꼴로 좌표를 받아 출력 좌표를 1/8로 줄였다. 또한 처음과 마지막이 연결되야 하기 때문에 마지막에 처음에 같은 좌표를 받아주었다.
![image](https://user-images.githubusercontent.com/32090903/63418068-6ea70700-c43d-11e9-88fd-954c8e3a0466.png)

**Comment by 3211187** [comment]
완료
---
 - 해당 JSON파일 형식을 만든다.
~~~
json_mask = dict()
    regions = dict()

    shape = dict()
    for i in range(3):
        shape["name"] = "polygon"
        shape["all_points_x"] = x
        shape["all_points_y"] = y

        re_attrib = dict()
        re_attrib["name"] = "hanja"

        num = dict()
        num["shape_attributes"] = shape
        num["region_attributes"] = re_attrib

        regions["%d" %i] = num

    name = dict()
    name["fileref"] = ""
    name["size"] = size
    name["filename"] = filename
    name["base64_img_data"] = ""
    name["file_attributes"] = {}
    name["regions"] = regions

    json_mask[filename_join] = name
~~~

 - 이후 받은 MASK영역 (x1,y1)을 해당하는 JSON영역 (shape)에 넣어주고 JSON파일을 저장한다.

 - 저장된 JSON파일을 VGG Tool에 연동시켜서 결과를 확인한다.

![image](https://user-images.githubusercontent.com/32090903/64219712-808aae80-cf01-11e9-952d-daeb0ab15237.png)

![image](https://user-images.githubusercontent.com/32090903/64219748-bb8ce200-cf01-11e9-9f31-2d9c3dd33e2f.png)

 - 영역을 수정하고 다시 JSON파일로 저장하면 Train Data 완성

추가 사항
---

1. 한 BBox 내에 여러개의 mask영역이 존재할 경우(이어지지 않고 따로따로 영역이 존재할 경우) 하나의 영역만 JSON파일로 받아지는 오류 존재

~~~
            v_len = len(v[:, 0])
            if v_len < max_len: continue

            max_len = v_len
~~~

 - mask영역을 잡을때마다 그 좌표를 담은 행렬의 길이를 측정
 - 같은 BBox영역의 mask영역이 받아지면 이전 좌표행렬길이와 비교
 - 길이가 긴것을 JSON파일에 저장
