### ISSUE TITLE
Mask-RCNN_source code

### ISSUE THREAD

**Issue by DBChoi85** [DBChoi85/Hanja_DKU#3]
현재 활용하는 source code의 경우 자유형태 boundary box만 처리 가능함.

box 및 circle 형태의 boundary box도 처리가능하게 해줄 필요가 있음.

**Comment by DBChoi85** [comment]
추가로 balloon.py 및 test.py 수정을 요함

전체적인 Path 설정, 사용하는 CNN model 설정

**Comment by 3211187** [comment]
balloon 는 coco와 같은 RCNN에서 활용가능한 데이터 형식들과 해당 모델들을 활용할수 있게만든 공용배포물이다. balloon.py는 이 balloondataset을 traindataset으로 이용할수 있도록 옵션을 설정해놓은 알고리즘이다. 따라서 형식만 맞춰준다면 따로 준비한 데이터들로 이 옵션들을 활용해 학습을 하는 것이 가능해 진다.
---
test.py(testing.py)는 balloon dataset으로 미리 학습된 모델을 불러와 balloon.py에 설정된 옵션을 사용해 주어진 이미지(test이미지)를 확인해 볼수 있도록 도와주는 알고리즘이다.
---
visualize.py는 기존에 제공하고 있는 mask r-cnn의 오픈소스에 들어가있는 파일중 하나로, 모델의 결과를 받아서 일정 형식으로 결과를 출력해 주는 알고리즘이 작성되어 있다.
---
balloon.py에서 굳이 고칠부분은 없고, test.py에서는 

class_names = ['BG', 'person', 'bicycle', 'car', 'motorcycle', 'airplane',
               'bus', 'train', 'truck', 'boat', 'traffic light', ...

에 우리가 학습한 라벨들을 추가해 준다.

IMAGE_DIR = 'C:\\Users\\ialab\\Desktop\\maskrcnn\\Mask_RCNN\\test2014\\'

에 우리가 test할 이미지들이 있는 폴더를 지정해 준다.

visualize.py에 display_instances()함수가 대부분의 처리를 담당하고 있다. 
(만약 test.py를 실행해서 에러가 발생시 display_instances()함수의 결과 이미지를 나타내는 plt.show()부분을 이미지를 저장하는 plt.savefig(...)형태로 바꿔주길 바란다.)
