### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by DBChoi85** [DBChoi85/Hanja_DKU#4]
한자학생들에서 시킬수 있는 GUI 구성 이슈

**Comment by 3211187** [comment]
![image](https://user-images.githubusercontent.com/32090903/63073918-de148680-bf65-11e9-9789-698ba0a6d142.png)

 - 이미지를 불러오는 버튼
 - 이미지를 라인별로 자르는 버튼
 - 잘린 이미지가 저장된 폴더를 여는 버튼
 - 지정한 이미지를 사용자가 원하는 크기로 Crop할수 있는 버튼
 - Crop한 이미지를 저장하는 버튼

으로 UI를 구성하였다.
